package moppydesk.kit;

import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 * @author Lukas
 */
public class MoppyKitUI extends javax.swing.JFrame {

    private final MoppyKitPlayerOutput[] outputs;

    public MoppyKitUI(final MoppyKitPlayerOutput... outputs) {
        this.outputs = outputs;
        initComponents();

        // Wenn eine Taste gedrückt wird, wird der nächste MoppyKitPlayerOutput 
        // gesucht, der aktuell keinen Ton spielt. Dieser spielt dann den Ton.
        // Wird die Taste losgelassen, wird der entsprechende 
        // MoppyKitPlayerOutput benachrichtigt.
        getToolkit().addAWTEventListener(new AWTEventListener() {
            @Override
            public void eventDispatched(AWTEvent event) {
                char key = ((KeyEvent) event).getKeyChar();
                int i;
                switch (event.getID()) {
                    case KeyEvent.KEY_PRESSED:
                        //System.out.println("Key pressed " + key);
                        i = 0;
                        do {
                            if (!outputs[i].isPlayingTone()) {
                                outputs[i].playToneForKey(key);
                                break;
                            }
                            i++;
                        } while (i < outputs.length);
                        break;
                    case KeyEvent.KEY_TYPED:
                        //keyTyped((KeyEvent) event);
                        break;
                    case KeyEvent.KEY_RELEASED:
                        //System.out.println("Key released " + key);
                        i = 0;
                        do {
                            if (outputs[i].getCurrentKey() == key) {
                                outputs[i].stopToneForKey(key);
                                break;
                            }
                            i++;
                        } while (i < outputs.length);
                        break;
                }
            }
        }, AWTEvent.KEY_EVENT_MASK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        panel.setAlignmentX(0.0F);
        panel.setAlignmentY(0.0F);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
